### ISSUE TITLE
Conflict for PYTHONHOME with conda

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/ansible-galaxy-extras#63]
In a fairly standard supervisor setup we get the following handler section
```
[program:handler]
command         = /home/galaxy/galaxy/.venv/bin/python ./lib/galaxy/main.py -c /home/galaxy/galaxy/config/galaxy.ini --server-name=handler%(process_num)s --log-file=/home/galaxy/galaxy/handler%(process_num)s.log
directory       = /home/galaxy/galaxy
process_name    = handler%(process_num)s
numprocs        = 1
umask           = 022
autostart       = true
autorestart     = true
startsecs       = 20
user            = galaxy
environment     = PYTHON_EGG_CACHE=/home/galaxy/.python-eggs, PYTHONHOME=/home/galaxy/galaxy.venv
startretries    = 15`
```

PYTHONHOME is in conflict with conda, so when trying to resolve a conda module we get:
```
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
Traceback (most recent call last):
  File "/home/galaxy/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
```

When removing PYTHONHOME we get
```
Traceback (most recent call last):
  File "/home/galaxy/galaxy/database/jobs/000/15/set_metadata_Smnwjn.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/home/galaxy/galaxy/lib/galaxy_ext/metadata/set_metadata.py", line 23, in <module>
    from sqlalchemy.orm import clear_mappers
ImportError: No module named sqlalchemy.orm
```

I'll have a try to see if we can just satisfy this by installing sqlalchemy into the conda root environment, but even if that works it's quite hacky. Suggestions, @bgruening @natefoo @jmchilton ?

**Comment by mvdbeek** [comment]
Alright, this can be done by adding
```
<env file="{{ galaxy_venv_dir }/bin/activate}" />
```
into job_conf.xml.j2

**Comment by natefoo** [comment]
@mvdbeek do you leave `$PYTHONHOME` in the handler env? We should probably include this in the dependencies page of the admin documentation.

**Comment by mvdbeek** [comment]
@natefoo no, we removed PYTHONHOME from the ansible-galaxy-extras role (and that's how we use it on our servers). I guess it would be a problem if PYTHONHOME was set when conda is in use.

**Comment by mvdbeek** [comment]
Yep:
```
(.venv)mariuss-MacBook-Pro:~ marius$ export PYTHONHOME=/Users/marius/src/galaxy/.venv/
(.venv)mariuss-MacBook-Pro:~ marius$ source ~/conda/bin/activate
Traceback (most recent call last):
  File "/Users/marius/conda/bin/conda", line 3, in <module>
    from conda.cli import main
ImportError: No module named conda.cli
```

**Comment by natefoo** [comment]
In this case we probably don't need a documentation update, then. None of our docs refer to putting `PYTHONHOME` in the supervisor environment.
